DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'tb_acesso' AND table_schema = 'public') THEN
        DROP TABLE tb_acesso;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'tb_ingresso' AND table_schema = 'public') THEN
        DROP TABLE tb_ingresso;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'tb_usuario' AND table_schema = 'public') THEN
        DROP TABLE tb_usuario;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'tb_filme' AND table_schema = 'public') THEN
        DROP TABLE tb_filme;
    END IF;
END $$;

create table tb_acesso (id bigint generated by default as identity, password varchar(255), username varchar(255), usuario_id bigint, primary key (id));
create table tb_filme (id bigint generated by default as identity, genero varchar(255), idade_minima integer, poltronas_disponiveis integer, tecnologia integer, tempo integer, titulo varchar(255), valor numeric(19,2), primary key (id));
create table tb_ingresso (id bigint generated by default as identity, filme_id bigint, usuario_id bigint, primary key (id));
create table tb_usuario (id bigint generated by default as identity, idade integer, nome varchar(255), role integer, primary key (id));
alter table tb_acesso add constraint UK_8ep305chap6qad80jodv8ha76 unique (username);
alter table tb_acesso add constraint FKo7j4d3h7p0bvp4lcn4cktg1ab foreign key (usuario_id) references tb_usuario;
alter table tb_ingresso add constraint FKt95laq1j4cnocb1l5nwj4jrh8 foreign key (filme_id) references tb_filme;
alter table tb_ingresso add constraint FKls4h071aiqq7honfirjs2f3x8 foreign key (usuario_id) references tb_usuario;


INSERT INTO tb_usuario (nome, idade, role) VALUES ('Alex Brown', 22, 1);
INSERT INTO tb_acesso (username, password, usuario_id) VALUES ('AlexBrown', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 1);

INSERT INTO tb_usuario (nome, idade, role) VALUES ('De Niro', 25, 1);
INSERT INTO tb_acesso (username, password, usuario_id) VALUES ('DeNiro', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 2);

INSERT INTO tb_usuario (nome, idade, role) VALUES ('Roberta Fernandes', 16, 0);
INSERT INTO tb_acesso (username, password, usuario_id) VALUES ('RobertaFernandes', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 3);

INSERT INTO tb_usuario (nome, idade, role) VALUES ('Julio Amorim Brown', 8, 0);
INSERT INTO tb_acesso (username, password, usuario_id) VALUES ('JulioAmorim', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 4);

INSERT INTO tb_usuario (nome, idade, role) VALUES ('Fernanda Neves', 20, 0);
INSERT INTO tb_acesso (username, password, usuario_id) VALUES ('FernandinhaNeves', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 5);

INSERT INTO tb_usuario (nome, idade, role) VALUES ('RodrigoSilva', 12, 0);
INSERT INTO tb_acesso (username, password, usuario_id) VALUES ('RodrigoSilva', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 6);

INSERT INTO tb_filme (titulo, genero, idade_minima, tempo, valor, tecnologia, poltronas_disponiveis) VALUES ('O Senhor dos Anéis', 'Aventura', 12, 180, 15, 1, 100);
INSERT INTO tb_filme (titulo, genero, idade_minima, tempo, valor, tecnologia, poltronas_disponiveis) VALUES ('O Hobbit', 'Aventura', 12, 180, 8, 0, 100);
INSERT INTO tb_filme (titulo, genero, idade_minima, tempo, valor, tecnologia, poltronas_disponiveis) VALUES ('V de Vingança', 'Ação', 14, 135, 10, 1, 100);
INSERT INTO tb_filme (titulo, genero, idade_minima, tempo, valor, tecnologia, poltronas_disponiveis) VALUES ('Django Livre', 'Ação', 16, 150, 12, 0, 100);
INSERT INTO tb_filme (titulo, genero, idade_minima, tempo, valor, tecnologia, poltronas_disponiveis) VALUES ('REC', 'Terror', 14, 120, 15, 0, 100);
INSERT INTO tb_filme (titulo, genero, idade_minima, tempo, valor, tecnologia, poltronas_disponiveis) VALUES ('Pulp Fiction', 'Drama', 16, 100, 16, 1, 100);
INSERT INTO tb_filme (titulo, genero, idade_minima, tempo, valor, tecnologia, poltronas_disponiveis) VALUES ('The Dark Knight', 'Ação', 16, 120, 20, 0, 100);
INSERT INTO tb_filme (titulo, genero, idade_minima, tempo, valor, tecnologia, poltronas_disponiveis) VALUES ('Inception', 'Sci-fi', 14, 95, 19, 1, 100);
INSERT INTO tb_filme (titulo, genero, idade_minima, tempo, valor, tecnologia, poltronas_disponiveis) VALUES ('O Tesouro Perdido', 'Aventura', 12, 125, 11, 1, 100);

INSERT INTO tb_ingresso (filme_id, usuario_id) VALUES (1,3);
INSERT INTO tb_ingresso (filme_id, usuario_id) VALUES (1,4);
INSERT INTO tb_ingresso (filme_id, usuario_id) VALUES (4,3);
INSERT INTO tb_ingresso (filme_id, usuario_id) VALUES (3,4);
INSERT INTO tb_ingresso (filme_id, usuario_id) VALUES (9,3);
INSERT INTO tb_ingresso (filme_id, usuario_id) VALUES (7,4);